### ISSUE TITLE
Use github id to get info

### ISSUE THREAD

**Issue by jwendell** [jwendell/gnome-shell-extension-timezone#8]
We could get, for instance, name and avatar from github.

**Comment by juanjosegzl** [comment]
Hi Jonh, cool extension you have here I have found it useful :+1: 

I'd like to know how do you plan to do this, my proposal:

* Adding github-id key to people.json
* Use github avatar and name if github-id is defined
* Use name or avatar instead of those fetched from github if they are present in .json

So let's say 'avatar' can overwrite github's avatar in case you want github's name but not its avatar.

what do you say?

**Comment by jwendell** [comment]
yep, that's exactly what I have in mind.

Actually I was about to start implementing this in a few minutes, but I'm more than happy if you are willing to do this :)

**Comment by juanjosegzl** [comment]
as you wish, it will take me a while to do this since I have not written a gnome extension ever :(

**Comment by jwendell** [comment]
Good!

Here's a snippet that does the tricky part: https://gist.github.com/jwendell/b3d90177932347efafae4b1c6d7b9b08

Inside the extension, you have to adapt this snippet to Avatar._setBackgroundImage(). Take a look at Avatar._getGravatarURL(); Create a similar method which returns the URL for github.

Let me know if you won't have time to work on this so that I can do it myself.

Have fun!

**Comment by jjgonzalez-tiempodev** [comment]
I wrote an implementation (very similar to this) last night. I'll send you the pull request ASAP

**Comment by juanjosegzl** [comment]
Hi Jonh, I have this change, I can query github's api and retrieve information but I am not able to get it out of that scope

https://github.com/juanjosegzl/gnome-shell-extension-timezone/commit/ba42f61917e9cc68bbd1a721128289e5044b2008

Do you know how to handle this scenario?

**Comment by jwendell** [comment]
Commented there
